---
  - name: Update to Amazon Linux servers
    hosts: amzservers

    tasks:
    - name: Copy sample1.txt to  Amazon Linux servers
      ansible.builtin.copy:
        src: /home/ec2-user/sample1.txt
        dest: /home/ec2-user/sample1.txt

  - name: Update to Ubuntu servers
    hosts: ubuntuservers

    tasks:
    - name: Copy sample1.txt to Ubuntu servers
      ansible.builtin.copy:
        src: /home/ec2-user/sample1.txt
        dest: /home/ubuntu/sample1.txt