---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Installing apache
        apt: name=apache2 state=present update_cache=yes
      - name: Ensure apache starts
        service: name=apache2 state=started enabled=yes 

  - hosts: webservers
    become: true
    tasks:
      - name: Installing services
        apt:
          name: 
            - apache2
            - php
          state: present
          update_cache: yes
      - name: Ensure apache starts
        service: name=apache2 state=started enabled=yes