AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Belt Exam 1 Day 3: Deploying a Python code snippet in AWS SAM

Resources:
  LambdaDevOpsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LambdaDevOps/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        LambdaDevOps:
          Type: Api
          Properties:
            Path: /LambdaDevOps
            Method: get

Outputs:
  LambdaDevOpsApi:
    Description: "API Gateway endpoint URL for Prod stage for LambdaDevOps function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/LambdaDevOps/"
  LambdaDevOpsFunction:
    Description: "LambdaDevOps Lambda Function ARN"
    Value: !GetAtt LambdaDevOpsFunction.Arn
  LambdaDevOpsFunctionIamRole:
    Description: "Implicit IAM Role created for LambdaDevOps function"
    Value: !GetAtt LambdaDevOpsFunctionRole.Arn
